"""create questions table

Revision ID: 9ebbb47127f7
Revises: 8dd1eee1314a
Create Date: 2026-10-03 07:38:52.780248

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ebbb47127f7"
down_revision: str | Sequence[str] | None = "8dd1eee1314a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum("easy", "medium", "hard", name="question_difficulty"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_questions_topic_id"), "questions", ["topic_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questions_topic_id"), table_name="questions")
    op.drop_table("questions")

    # Dropping `questions` doesn't guarantee
    # that generated downgrade() will clean up that type.
    #
    # Known alembic autogenerate issue:
    # autogenerated postgres Enum migrations
    # can leave the enum type behind on downgrade
    # According to alembic devs, it's recommended to manually drop it.
    #
    # Important, cause in case of upgrade -> downgrade -> upgrade,
    # will try to CREATE TYPE enum and get
    # ERROR: type already exists
    sa.Enum(
        "easy",
        "medium",
        "hard",
        name="question_difficulty",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
